default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: twito_development

test:
  <<: *default
  database: twito_test

production:
  <<: *default
  database: twito_production
  username: twito
  password: <%= ENV['TWITO_DATABASE_PASSWORD'] %>
